In [74]:
import numpy as np
bla = np.zeros((2,4))
bla

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
bla2 = np.array([[0, 2, 2, 0], [3, 3, 0, 0]]).astype(np.float32)
bla2

array([[0., 2., 2., 0.],
       [3., 3., 0., 0.]], dtype=float32)

In [76]:
bla = np.concatenate((bla, bla2), axis=0)
bla = np.concatenate((bla, np.zeros((1,4))), axis=0)
bla

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 2., 2., 0.],
       [3., 3., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
# blu = bla[np.sort(bla, axis=0, kind=None, order=None)]
blu = np.sort(bla, axis=1)
print(blu.shape)
blu

(5, 4)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 2., 2.],
       [0., 0., 3., 3.],
       [0., 0., 0., 0.]])

In [83]:
bli = np.argsort(blu[:,3])
print(bli.shape)
bli
# bli[:,0]

(5,)


array([0, 1, 4, 2, 3])

In [85]:
ble = np.flip(bli)
ble

array([3, 2, 4, 1, 0])

In [89]:
blo = bla[ble]
blo

array([[3., 3., 0., 0.],
       [0., 2., 2., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [90]:
bla = np.zeros((2,4))
bla2 = np.array([[0, 2, 2, 0], [3, 3, 0, 0]]).astype(np.float32)
bla = np.concatenate((bla, bla2), axis=0)
bla = np.concatenate((bla, np.zeros((1,4))), axis=0)
bla

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 2., 2., 0.],
       [3., 3., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
blu = np.sort(bla, axis=1)
bli = np.argsort(blu[:,-1])
ble = np.flip(bli)
blo = bla[ble]
blo

array([[3., 3., 0., 0.],
       [0., 2., 2., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])